logging:
  level:
    root: INFO
    nz:
      roag: DEBUG
server:
  port: ${SERVER_PORT}
  ssl:
    enabled: true
    key-store: ${SERVER_SSL_KEYSTORE}
    key-store-password: ${SERVER_SSL_KEYSTORE_PASSWORD}
    key-alias: ${SERVER_SSL_KEY_ALIAS}
    key-password: ${SERVER_SSL_KEY_PASSWORD}