logging:
  level:
    root: INFO
    nz:
      roag: DEBUG
server:
  port: ${SERVER_PORT}
  ssl:
    enabled: true
    keystore: /tomcat-ssl-keystore.jks
#    keystore: src/main/resources/tomcat-ssl-keystore.jks