# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:11.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: archery
      MARIADB_USER: robin
      MARIADB_PASSWORD: hood
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      context: .
    image: eurohlam/archery-logbook:1.0.9
    container_name: archery-logbook
    restart: always
    environment:
      SERVER_PORT: 7878
      SERVER_SSL_KEYSTORE: classpath:archery-logbook-keystore.jks
      SERVER_SSL_KEYSTORE_PASSWORD: changeit
      SERVER_SSL_KEY_ALIAS: archery-logbook
      SERVER_SSL_KEY_PASSWORD: changeit
      DB_URL: jdbc:mariadb://host.docker.internal:3306/archery
      DB_USER: robin
      DB_PWD: hood
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 7878:7878
    depends_on:
      - db


