# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: archery
      MARIADB_USER: robin
      MARIADB_PASSWORD: hood
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      context: .
    image: archer-logbook
    container_name: archer-logbook
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 7878:7878


