name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build a package with Maven
      run: mvn -B package --file pom.xml        

    - name: Show directory
      run: ls -lrt

    - name: Copy package to docker folder
      run: cp target/*.jar docker/
      
    - name: Build the Docker image
      run: cd docker && docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:0.1

    - name: Push the Docker image to repo
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}:0.1
