name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      imageVersion:
        description: "Docker image version"
        required: true

jobs:
  buildAndPush:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build a package with Maven
      run: mvn -B package --file pom.xml        

    - name: Show directory
      run: ls -lrt

    - name: Copy package to docker folder
      run: cp target/*.jar docker/

    - name: Log into docker registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ vars.DOCKER_REGISTRY }}
      
    - name: Build the Docker image
      run: cd docker && docker build . --file Dockerfile --tag ${{ vars.DOCKER_IMAGE_NAME }}:${{ inputs.imageVersion }}

    - name: Push the Docker image to repo
      run: docker push ${{ vars.DOCKER_IMAGE_NAME }}:${{ inputs.imageVersion }}
