name: Build a new release with Maven

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: View settings.xml
      run: cat /home/runner/.m2/settings.xml    

    - name: Configure Git user
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
      
    - name: Build with Maven
      run: mvn -DtagNameFormat=v@{project.version} release:prepare    
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_SECRET }}
